//! Game audio: one rodio device sink playing looping background music (via
//! a controllable `Player`) and fire-and-forget SFX (added straight to the
//! mixer), gated by the user's `Settings` and a session mute. The engine
//! makes no sound — SFX are derived at the `App` layer from state changes
//! (`audio_cues`), so `game.rs` stays audio-free.

use std::io::Cursor;
use std::sync::mpsc;
use std::thread;
use std::time::Duration;

use rodio::{Decoder, DeviceSinkBuilder, MixerDeviceSink, Player, Source};

use crate::{
    card::Card,
    game::{GamePhase, GameState, RoundOutcome},
    player::{Player as Side, PlayerState},
    settings::Settings,
};

/// The sound effects, one per game moment. Each maps to a short embedded
/// WAV clip generated by `scripts/gen_sfx.py` (synthesized, license-free).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Sfx {
    CardDraw,
    CardPlay,
    Flip,
    Stand,
    Bust,
    RoundWin,
    RoundLoss,
    RoundTie,
    GameWin,
    GameLoss,
    MenuMove,
    MenuSelect,
    MenuBack,
    /// The opponent's per-word murmur (spec 030), one per spoken word.
    Burble,
}

impl Sfx {
    /// The embedded WAV bytes for this effect.
    fn bytes(self) -> &'static [u8] {
        match self {
            Sfx::CardDraw => include_bytes!("../assets/sfx/card_draw.wav"),
            Sfx::CardPlay => include_bytes!("../assets/sfx/card_play.wav"),
            Sfx::Flip => include_bytes!("../assets/sfx/flip.wav"),
            Sfx::Stand => include_bytes!("../assets/sfx/stand.wav"),
            Sfx::Bust => include_bytes!("../assets/sfx/bust.wav"),
            Sfx::RoundWin => include_bytes!("../assets/sfx/round_win.wav"),
            Sfx::RoundLoss => include_bytes!("../assets/sfx/round_loss.wav"),
            Sfx::RoundTie => include_bytes!("../assets/sfx/round_tie.wav"),
            Sfx::GameWin => include_bytes!("../assets/sfx/game_win.wav"),
            Sfx::GameLoss => include_bytes!("../assets/sfx/game_loss.wav"),
            Sfx::MenuMove => include_bytes!("../assets/sfx/menu_move.wav"),
            Sfx::MenuSelect => include_bytes!("../assets/sfx/menu_select.wav"),
            Sfx::MenuBack => include_bytes!("../assets/sfx/menu_back.wav"),
            Sfx::Burble => include_bytes!("../assets/sfx/burble.wav"),
        }
    }
}

/// The looping background track, embedded like the SFX so the binary is
/// self-contained — no runtime asset dependency, so it plays no matter what
/// directory the binary is launched from. "Chipper Doodle" by Kevin MacLeod,
/// CC-BY 4.0, credited in `assets/CREDITS.md`.
const MUSIC_BYTES: &[u8] = include_bytes!("../assets/music/theme.mp3");

/// Commands the main thread sends to the audio thread. Everything the game
/// does audibly becomes one of these; sending is non-blocking.
enum AudioCommand {
    PlaySfx { sfx: Sfx, pitch: f32 },
    SetSettings(Settings),
    ToggleMute,
}

/// Handle to the audio thread. Constructing it is instant — it spawns the
/// thread and returns; the device open (which can take seconds the first
/// time a fresh binary touches the OS audio stack) happens on that thread,
/// so it never freezes the input loop. Every method just sends a command.
pub struct Audio {
    tx: mpsc::Sender<AudioCommand>,
}

/// The live rodio backend. The device sink is kept alive for the program
/// (its `Drop` stops all audio); the music `Player` loops the track.
struct Backend {
    sink: MixerDeviceSink,
    music: Player,
    has_music: bool,
}

impl Backend {
    fn open() -> Option<Self> {
        let sink = DeviceSinkBuilder::open_default_sink().ok()?;
        let music = Player::connect_new(sink.mixer());
        let has_music = load_music(&music);
        Some(Self { sink, music, has_music })
    }
}

/// Load the looping track into the music player (silent only if the
/// embedded track somehow fails to decode). Starts paused; `apply_music`
/// decides whether it plays.
fn load_music(music: &Player) -> bool {
    let Ok(source) = Decoder::new_looped(Cursor::new(MUSIC_BYTES)) else {
        return false;
    };
    music.append(source);
    music.pause();
    true
}

impl Audio {
    /// Spawn the audio thread and return a handle — instant. The device
    /// open happens on that thread, so it never freezes the input loop.
    /// Tests only construct this and drop it, so `cargo test` opens no
    /// audio device.
    pub fn new(settings: Settings) -> Self {
        let (tx, rx) = mpsc::channel();
        thread::spawn(move || audio_thread(rx, settings));
        Self { tx }
    }

    /// Play a one-shot effect at normal pitch (menu/settings clicks).
    pub fn play(&self, sfx: Sfx) {
        self.send(AudioCommand::PlaySfx { sfx, pitch: 1.0 });
    }

    /// Play an in-game cue — an SFX with its per-side pitch.
    pub fn play_cue(&self, cue: Cue) {
        self.send(AudioCommand::PlaySfx { sfx: cue.sfx, pitch: cue.pitch });
    }

    /// Adopt new settings (the Music/SFX/Voices volumes) and reconcile music.
    pub fn set_settings(&self, settings: Settings) {
        self.send(AudioCommand::SetSettings(settings));
    }

    /// Flip the session master mute and reconcile music.
    pub fn toggle_mute(&self) {
        self.send(AudioCommand::ToggleMute);
    }

    fn send(&self, cmd: AudioCommand) {
        // The audio thread only ends at program exit, so a send error just
        // means we're shutting down — drop it silently.
        let _ = self.tx.send(cmd);
    }
}

/// The audio thread body: open the device (blocking here is fine — it's
/// off the main thread), then serve commands until the handle is dropped.
fn audio_thread(rx: mpsc::Receiver<AudioCommand>, settings: Settings) {
    let mut state = AudioState {
        backend: Backend::open(),
        settings,
        muted: false,
    };
    // Opening the device can take seconds on a cold start (e.g. a Bluetooth
    // output waking — see plan.md). SFX cues the player queued by tapping
    // menu keys during that wait would otherwise all fire at once when it
    // finishes — a barrage against the spec's restraint rule. Drain and drop
    // that backlog now, but honor any settings/mute changes that queued.
    while let Ok(cmd) = rx.try_recv() {
        match cmd {
            AudioCommand::PlaySfx { .. } => {}
            AudioCommand::SetSettings(s) => state.settings = s,
            AudioCommand::ToggleMute => state.muted = !state.muted,
        }
    }
    state.apply_music();
    while let Ok(cmd) = rx.recv() {
        match cmd {
            AudioCommand::PlaySfx { sfx, pitch } => state.play(sfx, pitch),
            AudioCommand::SetSettings(s) => {
                state.settings = s;
                state.apply_music();
            }
            AudioCommand::ToggleMute => {
                state.muted = !state.muted;
                state.apply_music();
            }
        }
    }
}

/// The live audio state, owned entirely by the audio thread — the rodio
/// backend is `!Send`, so it must never leave that thread. A `None` backend
/// is a silent stub (no device: headless CI, no sound card) so the game
/// always runs.
struct AudioState {
    backend: Option<Backend>,
    settings: Settings,
    muted: bool,
}

impl AudioState {
    fn play(&self, sfx: Sfx, pitch: f32) {
        let Some(volume) = sfx_level(self.muted, sfx, self.settings) else { return };
        let Some(backend) = &self.backend else { return };
        if let Ok(source) = Decoder::new(Cursor::new(sfx.bytes())) {
            // `speed` shifts pitch (1.0 = normal); `amplify` sets volume.
            let source = source.speed(pitch).amplify(volume);
            backend.sink.mixer().add(source);
        }
    }

    /// Play the music when it should sound, pause it otherwise.
    fn apply_music(&self) {
        let Some(backend) = &self.backend else { return };
        if !backend.has_music {
            return;
        }
        if should_music_sound(self.muted, self.settings) {
            backend.music.set_volume(self.settings.music_volume);
            backend.music.play();
        } else {
            backend.music.pause();
        }
    }
}

/// Pure gating: should a SFX sound in this state? (Testable without a
/// device.) A zero volume is off, like the mute.
fn should_play_sfx(muted: bool, settings: Settings) -> bool {
    !muted && settings.sfx_volume > 0.0
}

/// The volume `sfx` plays at, or None when it is silent (spec 030, ruling
/// 10A): the burble on the Voices volume — silent when muted or at zero —
/// and every other effect on Sound FX, gated by `should_play_sfx`. Pure.
fn sfx_level(muted: bool, sfx: Sfx, settings: Settings) -> Option<f32> {
    match sfx {
        Sfx::Burble => (!muted && settings.voices_volume > 0.0).then_some(settings.voices_volume),
        _ => should_play_sfx(muted, settings).then_some(settings.sfx_volume),
    }
}

/// Pure gating: should the music be playing in this state?
fn should_music_sound(muted: bool, settings: Settings) -> bool {
    !muted && settings.music_volume > 0.0
}

/// A SFX plus a playback-speed factor (1.0 = normal). Speeding a clip up
/// or down shifts its pitch, so the opponent's actions can sound a touch
/// lower than the player's — telling the two apart by ear.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Cue {
    pub sfx: Sfx,
    pub pitch: f32,
}

/// How much lower the opponent's action sounds play than the player's.
/// Subtle on purpose — "very similar but slightly different." Easy to tune.
pub const OPPONENT_PITCH: f32 = 0.92;

/// Per-word pitch for the burble (spec 030): a small, fixed rise and fall
/// so a line reads as speech rather than one blip repeated. Tune by ear.
pub const BURBLE_PITCHES: [f32; 5] = [1.0, 0.94, 1.05, 0.97, 1.02];

/// The burble for word `i` of a line (0 = the first).
pub fn burble_cue(word: usize) -> Cue {
    Cue { sfx: Sfx::Burble, pitch: BURBLE_PITCHES[word % BURBLE_PITCHES.len()] }
}

/// The least time between two burbles (spec 030): longer than one burble at
/// its slowest pitch, so they never overlap and stack louder, and no more
/// than three loop ticks, so no word of an ordinary line is ever dropped
/// (plan §Design tension 3).
pub const BURBLE_GAP_MS: u64 = 150;

/// Whether a burble may play `since_last` after the previous one. Pure.
pub fn burble_clear(since_last: Duration) -> bool {
    since_last >= Duration::from_millis(BURBLE_GAP_MS)
}

/// A minimal snapshot of the game state's audible facts, for both sides.
/// `App` diffs successive snapshots to decide which SFX to play — the
/// engine itself never makes a sound. (No `PartialEq` — the diff runs
/// through `audio_cues`, and `RoundOutcome` isn't `Eq`.)
#[derive(Debug, Clone, Copy)]
pub struct AudioSnapshot {
    p_dealer: usize,
    p_played: usize,
    p_bust: bool,
    p_stood: bool,
    p_last_flip: bool,
    o_dealer: usize,
    o_played: usize,
    o_bust: bool,
    o_stood: bool,
    o_last_flip: bool,
    outcome: Option<RoundOutcome>,
    game_over: bool,
    player_won_game: bool,
}

impl AudioSnapshot {
    pub fn of(gs: &GameState) -> Self {
        let last_flip =
            |ps: &PlayerState| matches!(ps.played_row.last().map(|pc| pc.card), Some(Card::Flip(_)));
        let (game_over, player_won_game) = match gs.game_phase {
            GamePhase::GameOver { winner } => (true, matches!(winner, Side::Player)),
            _ => (false, false),
        };
        Self {
            p_dealer: gs.player.dealer_row.len(),
            p_played: gs.player.played_row.len(),
            p_bust: gs.player.bust,
            p_stood: gs.player.stood,
            p_last_flip: last_flip(&gs.player),
            o_dealer: gs.opponent.dealer_row.len(),
            o_played: gs.opponent.played_row.len(),
            o_bust: gs.opponent.bust,
            o_stood: gs.opponent.stood,
            o_last_flip: last_flip(&gs.opponent),
            outcome: gs.round_outcome,
            game_over,
            player_won_game,
        }
    }
}

/// The SFX to play for the transition `prev` → `curr`. Pure — the whole
/// truth table is unit-tested with no audio device. Covers both sides (so
/// the opponent's moves are heard); a bust suppresses that side's stand,
/// and a game-over replaces the round outcome cue.
pub fn audio_cues(prev: AudioSnapshot, curr: AudioSnapshot) -> Vec<Cue> {
    let mut cues = Vec::new();

    // (pitch, dealer_up, played_up, last_flip, bust_new, stood_new) — the
    // player at normal pitch, the opponent a touch lower.
    let per_side = [
        (
            1.0,
            curr.p_dealer > prev.p_dealer,
            curr.p_played > prev.p_played,
            curr.p_last_flip,
            curr.p_bust && !prev.p_bust,
            curr.p_stood && !prev.p_stood,
        ),
        (
            OPPONENT_PITCH,
            curr.o_dealer > prev.o_dealer,
            curr.o_played > prev.o_played,
            curr.o_last_flip,
            curr.o_bust && !prev.o_bust,
            curr.o_stood && !prev.o_stood,
        ),
    ];
    for (pitch, dealer_up, played_up, last_flip, bust_new, stood_new) in per_side {
        if dealer_up {
            cues.push(Cue { sfx: Sfx::CardDraw, pitch });
        }
        if played_up {
            let sfx = if last_flip { Sfx::Flip } else { Sfx::CardPlay };
            cues.push(Cue { sfx, pitch });
        }
        if bust_new {
            cues.push(Cue { sfx: Sfx::Bust, pitch }); // bust suppresses this side's stand
        } else if stood_new {
            cues.push(Cue { sfx: Sfx::Stand, pitch });
        }
    }

    // Outcomes are from the player's perspective — no per-side pitch. A
    // game-over replaces the round cue; a tie now has its own sound.
    let outcome = if curr.game_over && !prev.game_over {
        Some(if curr.player_won_game { Sfx::GameWin } else { Sfx::GameLoss })
    } else if curr.outcome.is_some() && prev.outcome.is_none() {
        Some(match curr.outcome {
            Some(RoundOutcome::PlayerWon) => Sfx::RoundWin,
            Some(RoundOutcome::OpponentWon) => Sfx::RoundLoss,
            _ => Sfx::RoundTie,
        })
    } else {
        None
    };
    if let Some(sfx) = outcome {
        cues.push(Cue { sfx, pitch: 1.0 });
    }

    cues
}

#[cfg(test)]
mod tests {
    use super::*;

    fn base() -> AudioSnapshot {
        AudioSnapshot {
            p_dealer: 0,
            p_played: 0,
            p_bust: false,
            p_stood: false,
            p_last_flip: false,
            o_dealer: 0,
            o_played: 0,
            o_bust: false,
            o_stood: false,
            o_last_flip: false,
            outcome: None,
            game_over: false,
            player_won_game: false,
        }
    }

    #[test]
    fn audio_gating_respects_mute_and_volume() {
        let on = Settings { music_volume: 0.5, sfx_volume: 0.8, ..Settings::default() };
        let silent = Settings { music_volume: 0.0, sfx_volume: 0.0, ..Settings::default() };
        assert!(should_play_sfx(false, on));
        assert!(!should_play_sfx(true, on)); // muted
        assert!(!should_play_sfx(false, silent)); // sfx volume 0
        assert!(should_music_sound(false, on));
        assert!(!should_music_sound(true, on)); // muted
        assert!(!should_music_sound(
            false,
            Settings { music_volume: 0.0, sfx_volume: 0.8, ..Settings::default() }
        ));
    }

    #[test]
    fn the_burble_follows_voices_and_nothing_else_does() {
        // Spec 030 (ruling 10A; AC 9, AC 17).
        let others = [
            Sfx::CardDraw,
            Sfx::CardPlay,
            Sfx::Flip,
            Sfx::Stand,
            Sfx::Bust,
            Sfx::RoundWin,
            Sfx::RoundLoss,
            Sfx::RoundTie,
            Sfx::GameWin,
            Sfx::GameLoss,
            Sfx::MenuMove,
            Sfx::MenuSelect,
            Sfx::MenuBack,
        ];
        let both = Settings { sfx_volume: 0.3, voices_volume: 0.7, ..Settings::default() };
        let no_voices = Settings { voices_volume: 0.0, ..both };
        let no_sfx = Settings { sfx_volume: 0.0, ..both };

        assert_eq!(sfx_level(false, Sfx::Burble, both), Some(0.7));
        assert_eq!(sfx_level(false, Sfx::Burble, no_voices), None);
        assert_eq!(sfx_level(false, Sfx::Burble, no_sfx), Some(0.7));
        assert_eq!(sfx_level(true, Sfx::Burble, both), None);
        for sfx in others {
            assert_eq!(sfx_level(false, sfx, both), Some(0.3), "{sfx:?}");
            assert_eq!(sfx_level(false, sfx, no_voices), Some(0.3), "{sfx:?}");
            assert_eq!(sfx_level(false, sfx, no_sfx), None, "{sfx:?}");
            assert_eq!(sfx_level(true, sfx, both), None, "{sfx:?}");
        }
    }

    // A player cue (normal pitch) and an opponent cue (lower pitch).
    fn pc(sfx: Sfx) -> Cue {
        Cue { sfx, pitch: 1.0 }
    }
    fn oc(sfx: Sfx) -> Cue {
        Cue { sfx, pitch: OPPONENT_PITCH }
    }

    #[test]
    fn cues_no_change_is_silent() {
        assert!(audio_cues(base(), base()).is_empty());
    }

    #[test]
    fn cues_draw_and_play_pitched_by_side() {
        let mut c = base();
        c.p_dealer = 1;
        assert_eq!(audio_cues(base(), c), vec![pc(Sfx::CardDraw)]);

        // The opponent's action is the same sound, a touch lower.
        let mut c = base();
        c.o_dealer = 1;
        assert_eq!(audio_cues(base(), c), vec![oc(Sfx::CardDraw)]);

        let mut c = base();
        c.p_played = 1;
        assert_eq!(audio_cues(base(), c), vec![pc(Sfx::CardPlay)]);

        let mut c = base();
        c.o_played = 1;
        assert_eq!(audio_cues(base(), c), vec![oc(Sfx::CardPlay)]);
    }

    #[test]
    fn cues_a_played_flip_is_the_flip_sound() {
        let mut c = base();
        c.p_played = 1;
        c.p_last_flip = true;
        assert_eq!(audio_cues(base(), c), vec![pc(Sfx::Flip)]);
    }

    #[test]
    fn cues_stand_and_bust_suppresses_stand() {
        let mut c = base();
        c.p_stood = true;
        assert_eq!(audio_cues(base(), c), vec![pc(Sfx::Stand)]);

        // Standing into a bust: only the bust sounds, not the stand.
        let mut c = base();
        c.p_stood = true;
        c.p_bust = true;
        assert_eq!(audio_cues(base(), c), vec![pc(Sfx::Bust)]);
    }

    #[test]
    fn cues_round_outcomes_include_a_distinct_tie() {
        let mut c = base();
        c.outcome = Some(RoundOutcome::PlayerWon);
        assert_eq!(audio_cues(base(), c), vec![pc(Sfx::RoundWin)]);

        let mut c = base();
        c.outcome = Some(RoundOutcome::OpponentWon);
        assert_eq!(audio_cues(base(), c), vec![pc(Sfx::RoundLoss)]);

        // A tie now has its own sound (it used to be silent).
        let mut c = base();
        c.outcome = Some(RoundOutcome::Tied);
        assert_eq!(audio_cues(base(), c), vec![pc(Sfx::RoundTie)]);
    }

    #[test]
    fn cues_game_over_replaces_the_round_cue() {
        // A game-winning round sets both outcome and game_over in one step;
        // only the game cue should play.
        let mut c = base();
        c.outcome = Some(RoundOutcome::PlayerWon);
        c.game_over = true;
        c.player_won_game = true;
        assert_eq!(audio_cues(base(), c), vec![pc(Sfx::GameWin)]);

        let mut c = base();
        c.outcome = Some(RoundOutcome::OpponentWon);
        c.game_over = true;
        c.player_won_game = false;
        assert_eq!(audio_cues(base(), c), vec![pc(Sfx::GameLoss)]);
    }

    #[test]
    fn cues_do_not_repeat_once_the_flag_is_already_set() {
        // outcome already Some in prev → no new round cue
        let mut prev = base();
        prev.outcome = Some(RoundOutcome::PlayerWon);
        let mut curr = prev;
        curr.p_dealer = 1; // some unrelated change
        assert_eq!(audio_cues(prev, curr), vec![pc(Sfx::CardDraw)]);
    }

    // The burble's loudest sample against the music's RMS over its first
    // 60 s (plan §Design tension 9), scaled by the default volumes. Decodes
    // the embedded assets only; opens no audio device.
    #[test]
    fn the_burble_is_softer_than_the_music() {
        let burble = Decoder::new(Cursor::new(Sfx::Burble.bytes())).unwrap();
        let peak = burble.map(|s| (s as f64).abs()).fold(0.0, f64::max);

        let music = Decoder::new(Cursor::new(MUSIC_BYTES)).unwrap();
        let window = 60 * music.sample_rate().get() as usize * music.channels().get() as usize;
        let (sum, count) = music
            .take(window)
            .fold((0.0, 0usize), |(sum, count), s| (sum + (s as f64).powi(2), count + 1));
        let rms = (sum / count as f64).sqrt();

        let d = Settings::default();
        let ceiling = rms * d.music_volume as f64 / d.sfx_volume as f64;
        println!("burble peak {peak:.4}");
        println!("music rms {rms:.4} over its first 60 s; ceiling {ceiling:.4}");
        assert!(peak <= ceiling, "burble peak {peak} above the ceiling {ceiling}");
    }

    #[test]
    fn a_burble_ends_before_the_next_can_start() {
        let burble = Decoder::new(Cursor::new(Sfx::Burble.bytes())).unwrap();
        let per_second = burble.sample_rate().get() as f64 * burble.channels().get() as f64;
        let length_ms = burble.count() as f64 / per_second * 1000.0;
        let slowest = BURBLE_PITCHES.iter().copied().fold(f32::INFINITY, f32::min) as f64;
        // `speed(pitch)` below 1.0 stretches the clip.
        assert!(length_ms / slowest <= BURBLE_GAP_MS as f64);
        assert!(BURBLE_GAP_MS <= 3 * crate::GAME_LOOP_SLEEP_MS);
    }

    #[test]
    fn burbles_are_spaced_by_the_gap() {
        assert!(!burble_clear(Duration::ZERO));
        assert!(!burble_clear(Duration::from_millis(BURBLE_GAP_MS - 1)));
        assert!(burble_clear(Duration::from_millis(BURBLE_GAP_MS)));
        assert!(burble_clear(Duration::from_millis(BURBLE_GAP_MS + 1)));
        assert!(burble_clear(Duration::MAX));
    }

    #[test]
    fn each_word_has_its_own_burble_pitch() {
        let n = BURBLE_PITCHES.len();
        for i in 0..n {
            let cue = burble_cue(i);
            assert_eq!(cue.sfx, Sfx::Burble);
            assert!((0.9..=1.1).contains(&cue.pitch), "word {i}: {}", cue.pitch);
            assert_ne!(cue.pitch, burble_cue(i + 1).pitch, "words {i} and {}", i + 1);
        }
        // Past the table's end, the pitches wrap.
        assert_eq!(burble_cue(n), burble_cue(0));
        assert_eq!(burble_cue(n + 2), burble_cue(2));
    }
}
