//! Game audio: one rodio device sink playing looping background music (via
//! a controllable `Player`) and fire-and-forget SFX (added straight to the
//! mixer), gated by the user's `Settings` and a session mute. The engine
//! makes no sound — SFX are derived at the `App` layer from state changes
//! (`audio_cues`), so `game.rs` stays audio-free.

use std::io::{BufReader, Cursor};

use rodio::{Decoder, DeviceSinkBuilder, MixerDeviceSink, Player};

use crate::{
    card::Card,
    game::{GamePhase, GameState, RoundOutcome},
    player::{Player as Side, PlayerState},
    settings::Settings,
};

/// The sound effects, one per game moment. Each maps to a short embedded
/// WAV clip generated by `scripts/gen_sfx.py` (synthesized, license-free).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Sfx {
    CardDraw,
    CardPlay,
    Flip,
    Stand,
    Bust,
    RoundWin,
    RoundLoss,
    GameWin,
    GameLoss,
    MenuMove,
    MenuSelect,
}

impl Sfx {
    /// The embedded WAV bytes for this effect.
    fn bytes(self) -> &'static [u8] {
        match self {
            Sfx::CardDraw => include_bytes!("../assets/sfx/card_draw.wav"),
            Sfx::CardPlay => include_bytes!("../assets/sfx/card_play.wav"),
            Sfx::Flip => include_bytes!("../assets/sfx/flip.wav"),
            Sfx::Stand => include_bytes!("../assets/sfx/stand.wav"),
            Sfx::Bust => include_bytes!("../assets/sfx/bust.wav"),
            Sfx::RoundWin => include_bytes!("../assets/sfx/round_win.wav"),
            Sfx::RoundLoss => include_bytes!("../assets/sfx/round_loss.wav"),
            Sfx::GameWin => include_bytes!("../assets/sfx/game_win.wav"),
            Sfx::GameLoss => include_bytes!("../assets/sfx/game_loss.wav"),
            Sfx::MenuMove => include_bytes!("../assets/sfx/menu_move.wav"),
            Sfx::MenuSelect => include_bytes!("../assets/sfx/menu_select.wav"),
        }
    }
}

/// Where the looping music track is loaded from at runtime. Kept a runtime
/// path (not embedded) so the audio core builds and tests before the CC0
/// track is sourced (spec 004 T008); absent → silent.
const MUSIC_PATH: &str = "assets/music/theme.ogg";

/// The audio player. Holds the rodio backend when a device is available,
/// or `None` (a silent stub) when there is no device — headless CI, no
/// sound card — so the game always runs.
pub struct Audio {
    backend: Option<Backend>,
    settings: Settings,
    muted: bool,
}

/// The live rodio backend. The device sink is kept alive for the program
/// (its `Drop` stops all audio); the music `Player` loops the track.
struct Backend {
    sink: MixerDeviceSink,
    music: Player,
    has_music: bool,
}

impl Backend {
    fn open() -> Option<Self> {
        let sink = DeviceSinkBuilder::open_default_sink().ok()?;
        let music = Player::connect_new(sink.mixer());
        let has_music = load_music(&music);
        Some(Self { sink, music, has_music })
    }
}

/// Load the looping track into the music player (silent if the file is
/// absent). Starts paused; `apply_music` decides whether it plays.
fn load_music(music: &Player) -> bool {
    let Ok(file) = std::fs::File::open(MUSIC_PATH) else {
        return false;
    };
    let Ok(source) = Decoder::new_looped(BufReader::new(file)) else {
        return false;
    };
    music.append(source);
    music.pause();
    true
}

impl Audio {
    /// Open the audio backend (or a silent stub if none is available) and
    /// bring the music into line with the initial settings.
    pub fn new(settings: Settings) -> Self {
        let audio = Self {
            backend: Backend::open(),
            settings,
            muted: false,
        };
        audio.apply_music();
        audio
    }

    /// Play a one-shot effect — a no-op unless SFX are on and not muted.
    pub fn play(&self, sfx: Sfx) {
        if !should_play_sfx(self.muted, self.settings) {
            return;
        }
        let Some(backend) = &self.backend else { return };
        if let Ok(source) = Decoder::new(Cursor::new(sfx.bytes())) {
            backend.sink.mixer().add(source);
        }
    }

    /// Adopt new settings (e.g. the Music/SFX toggles) and reconcile music.
    pub fn set_settings(&mut self, settings: Settings) {
        self.settings = settings;
        self.apply_music();
    }

    /// Flip the session master mute and reconcile music.
    pub fn toggle_mute(&mut self) {
        self.muted = !self.muted;
        self.apply_music();
    }

    /// The one place that reconciles the music sink with the current state:
    /// play the loop when music should sound, pause it otherwise.
    fn apply_music(&self) {
        let Some(backend) = &self.backend else { return };
        if !backend.has_music {
            return;
        }
        if should_music_sound(self.muted, self.settings) {
            backend.music.play();
        } else {
            backend.music.pause();
        }
    }
}

/// Pure gating: should a SFX sound in this state? (Testable without a device.)
fn should_play_sfx(muted: bool, settings: Settings) -> bool {
    !muted && settings.sfx
}

/// Pure gating: should the music be playing in this state?
fn should_music_sound(muted: bool, settings: Settings) -> bool {
    !muted && settings.music
}

/// A minimal snapshot of the game state's audible facts, for both sides.
/// `App` diffs successive snapshots to decide which SFX to play — the
/// engine itself never makes a sound. (No `PartialEq` — the diff runs
/// through `audio_cues`, and `RoundOutcome` isn't `Eq`.)
#[derive(Debug, Clone, Copy)]
pub struct AudioSnapshot {
    p_dealer: usize,
    p_played: usize,
    p_bust: bool,
    p_stood: bool,
    p_last_flip: bool,
    o_dealer: usize,
    o_played: usize,
    o_bust: bool,
    o_stood: bool,
    o_last_flip: bool,
    outcome: Option<RoundOutcome>,
    game_over: bool,
    player_won_game: bool,
}

impl AudioSnapshot {
    pub fn of(gs: &GameState) -> Self {
        let last_flip =
            |ps: &PlayerState| matches!(ps.played_row.last().map(|pc| pc.card), Some(Card::Flip(_)));
        let (game_over, player_won_game) = match gs.game_phase {
            GamePhase::GameOver { winner } => (true, matches!(winner, Side::Player)),
            _ => (false, false),
        };
        Self {
            p_dealer: gs.player.dealer_row.len(),
            p_played: gs.player.played_row.len(),
            p_bust: gs.player.bust,
            p_stood: gs.player.stood,
            p_last_flip: last_flip(&gs.player),
            o_dealer: gs.opponent.dealer_row.len(),
            o_played: gs.opponent.played_row.len(),
            o_bust: gs.opponent.bust,
            o_stood: gs.opponent.stood,
            o_last_flip: last_flip(&gs.opponent),
            outcome: gs.round_outcome,
            game_over,
            player_won_game,
        }
    }
}

/// The SFX to play for the transition `prev` → `curr`. Pure — the whole
/// truth table is unit-tested with no audio device. Covers both sides (so
/// the opponent's moves are heard); a bust suppresses that side's stand,
/// and a game-over replaces the round outcome cue.
pub fn audio_cues(prev: AudioSnapshot, curr: AudioSnapshot) -> Vec<Sfx> {
    let mut cues = Vec::new();

    let per_side = [
        (
            curr.p_dealer > prev.p_dealer,
            curr.p_played > prev.p_played,
            curr.p_last_flip,
            curr.p_bust && !prev.p_bust,
            curr.p_stood && !prev.p_stood,
        ),
        (
            curr.o_dealer > prev.o_dealer,
            curr.o_played > prev.o_played,
            curr.o_last_flip,
            curr.o_bust && !prev.o_bust,
            curr.o_stood && !prev.o_stood,
        ),
    ];
    for (dealer_up, played_up, last_flip, bust_new, stood_new) in per_side {
        if dealer_up {
            cues.push(Sfx::CardDraw);
        }
        if played_up {
            cues.push(if last_flip { Sfx::Flip } else { Sfx::CardPlay });
        }
        if bust_new {
            cues.push(Sfx::Bust); // bust suppresses this side's stand
        } else if stood_new {
            cues.push(Sfx::Stand);
        }
    }

    if curr.game_over && !prev.game_over {
        cues.push(if curr.player_won_game {
            Sfx::GameWin
        } else {
            Sfx::GameLoss
        });
    } else if curr.outcome.is_some() && prev.outcome.is_none() {
        match curr.outcome {
            Some(RoundOutcome::PlayerWon) => cues.push(Sfx::RoundWin),
            Some(RoundOutcome::OpponentWon) => cues.push(Sfx::RoundLoss),
            _ => {} // a tie is silent
        }
    }

    cues
}

#[cfg(test)]
mod tests {
    use super::*;

    fn base() -> AudioSnapshot {
        AudioSnapshot {
            p_dealer: 0,
            p_played: 0,
            p_bust: false,
            p_stood: false,
            p_last_flip: false,
            o_dealer: 0,
            o_played: 0,
            o_bust: false,
            o_stood: false,
            o_last_flip: false,
            outcome: None,
            game_over: false,
            player_won_game: false,
        }
    }

    #[test]
    fn audio_gating_respects_mute_and_channels() {
        let on = Settings { music: true, sfx: true };
        let off = Settings { music: false, sfx: false };
        assert!(should_play_sfx(false, on));
        assert!(!should_play_sfx(true, on)); // muted
        assert!(!should_play_sfx(false, off)); // sfx off
        assert!(should_music_sound(false, on));
        assert!(!should_music_sound(true, on)); // muted
        assert!(!should_music_sound(false, Settings { music: false, sfx: true }));
    }

    #[test]
    fn cues_no_change_is_silent() {
        assert!(audio_cues(base(), base()).is_empty());
    }

    #[test]
    fn cues_draw_and_play_for_either_side() {
        let mut c = base();
        c.p_dealer = 1;
        assert_eq!(audio_cues(base(), c), vec![Sfx::CardDraw]);

        let mut c = base();
        c.o_dealer = 1;
        assert_eq!(audio_cues(base(), c), vec![Sfx::CardDraw]);

        let mut c = base();
        c.p_played = 1;
        assert_eq!(audio_cues(base(), c), vec![Sfx::CardPlay]);

        let mut c = base();
        c.o_played = 1;
        assert_eq!(audio_cues(base(), c), vec![Sfx::CardPlay]);
    }

    #[test]
    fn cues_a_played_flip_is_the_flip_sound() {
        let mut c = base();
        c.p_played = 1;
        c.p_last_flip = true;
        assert_eq!(audio_cues(base(), c), vec![Sfx::Flip]);
    }

    #[test]
    fn cues_stand_and_bust_suppresses_stand() {
        let mut c = base();
        c.p_stood = true;
        assert_eq!(audio_cues(base(), c), vec![Sfx::Stand]);

        // Standing into a bust: only the bust sounds, not the stand.
        let mut c = base();
        c.p_stood = true;
        c.p_bust = true;
        assert_eq!(audio_cues(base(), c), vec![Sfx::Bust]);
    }

    #[test]
    fn cues_round_outcomes_and_tie_silence() {
        let mut c = base();
        c.outcome = Some(RoundOutcome::PlayerWon);
        assert_eq!(audio_cues(base(), c), vec![Sfx::RoundWin]);

        let mut c = base();
        c.outcome = Some(RoundOutcome::OpponentWon);
        assert_eq!(audio_cues(base(), c), vec![Sfx::RoundLoss]);

        let mut c = base();
        c.outcome = Some(RoundOutcome::Tied);
        assert!(audio_cues(base(), c).is_empty()); // tie is silent
    }

    #[test]
    fn cues_game_over_replaces_the_round_cue() {
        // A game-winning round sets both outcome and game_over in one step;
        // only the game cue should play.
        let mut c = base();
        c.outcome = Some(RoundOutcome::PlayerWon);
        c.game_over = true;
        c.player_won_game = true;
        assert_eq!(audio_cues(base(), c), vec![Sfx::GameWin]);

        let mut c = base();
        c.outcome = Some(RoundOutcome::OpponentWon);
        c.game_over = true;
        c.player_won_game = false;
        assert_eq!(audio_cues(base(), c), vec![Sfx::GameLoss]);
    }

    #[test]
    fn cues_do_not_repeat_once_the_flag_is_already_set() {
        // outcome already Some in prev → no new round cue
        let mut prev = base();
        prev.outcome = Some(RoundOutcome::PlayerWon);
        let mut curr = prev;
        curr.p_dealer = 1; // some unrelated change
        assert_eq!(audio_cues(prev, curr), vec![Sfx::CardDraw]);
    }
}
